# Generated by Django 2.2.10 on 2020-02-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrecipe', '0002_auto_20200214_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddetail',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
