# Generated by Django 2.2.10 on 2020-02-14 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodrecipe', '0003_auto_20200214_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddetail',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
